# Generated by Django 4.2.4 on 2023-08-04 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('tg_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='id Telegram')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username в Telegram')),
                ('fullname', models.CharField(max_length=255, verbose_name='ФИО в Telegram')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message="The phone number must be specified in the following format: '+79012345678'.", regex='^\\+\\d{11,20}')], verbose_name='номер телефона')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
    ]
