# Generated by Django 4.2.4 on 2023-08-04 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('message', models.TextField(blank=True, max_length=3000, verbose_name='сообщение')),
                ('status', models.CharField(choices=[('0', 'Закрытая'), ('1', 'Новая'), ('2', 'В процессе')], default='1', max_length=30, verbose_name='статус')),
                ('comment', models.TextField(blank=True, max_length=10000, null=True, verbose_name='комментарий администратора')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='app_telegram.tguser', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'заявка на звонок',
                'verbose_name_plural': 'заявки на звонок',
            },
        ),
    ]
